// <auto-generated />
namespace VotingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202103270302013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202103270302013));
        
        string IMigrationMetadata.Id
        {
            get { return "202103270356446_202103270302013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
